openapi: 3.0.0
info:
  title: Schedule Meeting
  description: REST API to Schedule Meetings with different Users in specified Rooms by Umesh Thakre
  version: 1.0.1

servers:
  - url: http://localhost:4000
    description: REST API is deployed on render


paths:
  /:
    get:
      summary: Returns a JSON Object.
      description: JSON Object with message says running successfully.
      responses:
        '200':    # status code
          description:  Returns a JSON Object.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /user/createuser:
    post:
      summary: Accepts a username and create a new user the database
      requestBody:
       description: Accepts a username and create a new user the database
       required: true
       content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
      description: Accepts a username and create a new user the database. The entered user must be unique otherwise an error is returned
      responses:
        '200':    # status code
          description:  Returns a JSON Object with user details
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  success:
                    type: boolean
                  username:
                    type: string

        '403':
          description:  Returns a JSON Object with Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  success:
                    type: boolean

  /room/createroom:
    post:
      summary: Accepts a roomId and create a new room in the database
      requestBody:
       description: Accepts a roomId and create a new room in the database
       required: true
       content:
          application/json:
            schema:
              type: object
              properties:
                roomId:
                  type: string
      description: Accepts a room id and create a new room the database. The entered room id  must be unique otherwise an error is returned
      responses:
        '200':    # status code
          description:  Returns a JSON Object with user details
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  success:
                    type: boolean
                  username:
                    type: string

        '403':
          description:  Returns a JSON Object with Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  success:
                    type: boolean

  /meetings/schedulemeeting:
    post:
      summary: Accepts various details as given in the description to schedule a meeting
      requestBody:
       description: Accepts various details as given in the description to schedule a meeting with various users which are in the database in a room with given roomId
       required: true
       content:
          application/json:
            schema:
              type: object
              properties:
                users:
                  type: array
                  items:
                    type: string
                dateOfMeeting: 
                  type: string
                meetingStart:
                  type: string
                meetingEnd:
                  type: string
                roomId:
                  type: string
              example:
                users: ["User1","User2"]
                dateOfMeeting: 2022/10/27
                meetingStart: 9:00
                meetingEnd: 18:00
                roomId: R1

      description: Accepts a room id and create a new room the database. The entered room id  must be unique otherwise an error is returned. Value of meetingStart and meetingEnd must always be in 24 hours format
      responses:
        '200':    # status code
          description:  Returns a JSON Object with user details
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  success:
                    type: boolean
                  username:
                    type: string

        '403':
          description:  Returns a JSON Object with Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  success:
                    type: boolean

                  
                    

  
# paths:
#   /:
#     get:
#       summary: returns message which says running successfully
#       responses:
#         '200':
#         description: returns a json object with message 
#         content:
#           application/json:
#             schema:
#               type: object
#               properties:
#                 success: boolean
#                 messsage: string